# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gchat.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bgchat.proto\x12\x05greet\"-\n\x0b\x43hatRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08greeting\x18\x02 \x01(\t\"\x1c\n\tChatReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"D\n\x0c\x44\x65layedReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12#\n\x07request\x18\x02 \x03(\x0b\x32\x12.greet.ChatRequest2\xeb\x01\n\x04\x43hat\x12\x32\n\nSingleCall\x12\x12.greet.ChatRequest\x1a\x10.greet.ChatReply\x12\x38\n\x0eStreamToClient\x12\x12.greet.ChatRequest\x1a\x10.greet.ChatReply0\x01\x12;\n\x0eStreamToServer\x12\x12.greet.ChatRequest\x1a\x13.greet.DelayedReply(\x01\x12\x38\n\x0cMutualStream\x12\x12.greet.ChatRequest\x1a\x10.greet.ChatReply(\x01\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gchat_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CHATREQUEST._serialized_start=22
  _CHATREQUEST._serialized_end=67
  _CHATREPLY._serialized_start=69
  _CHATREPLY._serialized_end=97
  _DELAYEDREPLY._serialized_start=99
  _DELAYEDREPLY._serialized_end=167
  _CHAT._serialized_start=170
  _CHAT._serialized_end=405
# @@protoc_insertion_point(module_scope)
